%YAML:1.0
DumpFilePoses: "/home/socrob/isam2_ws/src/isam2/results/April15/poses_test_1.txt"
DumpFileLandmarks: "/home/socrob/isam2_ws/src/isam2/results/April15/landmarks_test_1.txt"

BATCH: 0

DEBUG: 1

INCREMENTAL_UPDATE: 1

MAX_POSES_BATCH: 100

RVIZ_VISUALIZATION: 1

IMAGE_SPACE_VISUALIZATION: 1


%%%%TODO: add LM and iSAM2 parameters also here

